
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package soaphw;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-21T21:27:16.824+01:00
 * Generated source version: 3.5.1
 *
 */

@javax.jws.WebService(
                      serviceName = "TenderWSImplService",
                      portName = "TenderWSImplPort",
                      targetNamespace = "http://soaphw/",
                      wsdlLocation = "http://127.0.0.1:8000/TenderWS?wsdl",
                      endpointInterface = "soaphw.TenderWS")

public class TenderWSImplPortImpl implements TenderWS {

    private static final Logger LOG = Logger.getLogger(TenderWSImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see soaphw.TenderWS#changeTenderName(int arg0, java.lang.String arg1)*
     */
    public java.lang.String changeTenderName(int arg0, java.lang.String arg1) {
        LOG.info("Executing operation changeTenderName");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return1489438888";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see soaphw.TenderWS#getTender(int arg0)*
     */
    public java.lang.String getTender(int arg0) {
        LOG.info("Executing operation getTender");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1514525961";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
