package soaphw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-21T21:27:16.833+01:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://soaphw/", name = "TenderWS")
@XmlSeeAlso({ObjectFactory.class})
public interface TenderWS {

    @WebMethod
    @Action(input = "http://soaphw/TenderWS/changeTenderNameRequest", output = "http://soaphw/TenderWS/changeTenderNameResponse")
    @RequestWrapper(localName = "changeTenderName", targetNamespace = "http://soaphw/", className = "soaphw.ChangeTenderName")
    @ResponseWrapper(localName = "changeTenderNameResponse", targetNamespace = "http://soaphw/", className = "soaphw.ChangeTenderNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String changeTenderName(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://soaphw/TenderWS/getTenderRequest", output = "http://soaphw/TenderWS/getTenderResponse")
    @RequestWrapper(localName = "getTender", targetNamespace = "http://soaphw/", className = "soaphw.GetTender")
    @ResponseWrapper(localName = "getTenderResponse", targetNamespace = "http://soaphw/", className = "soaphw.GetTenderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getTender(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
