
package soaphw;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-21T21:27:16.778+01:00
 * Generated source version: 3.5.1
 *
 */
public final class TenderWS_TenderWSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soaphw/", "TenderWSImplService");

    private TenderWS_TenderWSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TenderWSImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TenderWSImplService ss = new TenderWSImplService(wsdlURL, SERVICE_NAME);
        TenderWS port = ss.getTenderWSImplPort();

        {
        System.out.println("Invoking changeTenderName...");
        int _changeTenderName_arg0 = 15001;
        java.lang.String _changeTenderName_arg1 = "new name";
        java.lang.String _changeTenderName__return = port.changeTenderName(_changeTenderName_arg0, _changeTenderName_arg1);
        System.out.println("changeTenderName.result=" + _changeTenderName__return);


        }
        {
        System.out.println("Invoking getTender...");
        int _getTender_arg0 = 15002;
        java.lang.String _getTender__return = port.getTender(_getTender_arg0);
        System.out.println("getTender.result=" + _getTender__return);


        }

        System.exit(0);
    }

}
