package soaphw;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-21T21:27:16.837+01:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "TenderWSImplService",
                  wsdlLocation = "http://127.0.0.1:8000/TenderWS?wsdl",
                  targetNamespace = "http://soaphw/")
public class TenderWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soaphw/", "TenderWSImplService");
    public final static QName TenderWSImplPort = new QName("http://soaphw/", "TenderWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8000/TenderWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TenderWSImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8000/TenderWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TenderWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TenderWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TenderWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TenderWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TenderWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TenderWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TenderWS
     */
    @WebEndpoint(name = "TenderWSImplPort")
    public TenderWS getTenderWSImplPort() {
        return super.getPort(TenderWSImplPort, TenderWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TenderWS
     */
    @WebEndpoint(name = "TenderWSImplPort")
    public TenderWS getTenderWSImplPort(WebServiceFeature... features) {
        return super.getPort(TenderWSImplPort, TenderWS.class, features);
    }

}
